package enuygunpom.constants;

import org.openqa.selenium.By;

public class Constants {
    public static By allInTrip = By.xpath("//android.widget.ImageButton[@resource-id='com.mobilatolye.android.enuygun:id/btnClose']");
    public static By closeMemmberScreen = By.xpath("//android.widget.ImageButton[@resource-id='com.mobilatolye.android.enuygun:id/txtClose']");
    public static By signUp = By.xpath("//android.widget.LinearLayout[@content-desc='Üye ol']");
    public static By eMail = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/price_alarm_email_input']");
    public static By password = By.xpath("//android.widget.EditText[@content-desc='loginPasswordTextField']");
    public static By showPassword = By.xpath("//android.widget.ImageView[@content-desc='loginShowPasswordButton']");
    public static By loginButton = By.xpath("//android.widget.Button[@content-desc='loginButton']");
    public static By wrongPasswordOrEmail = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/md_buttonDefaultPositive']");
    public static By forgetPassword = By.xpath("//android.widget.TextView[@content-desc='forgotPasswordButton']");
    public static By forgetPasswordEmail = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/edtEmail']");
    public static By sendCodeToMail = By.xpath("//android.widget.Button[@resource-id='com.mobilatolye.android.enuygun:id/txtResetPassword']");
    public static By sendedCode = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/md_buttonDefaultPositive']");
    public static By signIn = By.xpath("//android.widget.LinearLayout[@content-desc='Giriş yap']");
    public static By oneWay = By.xpath("//android.widget.RadioButton[@resource-id='com.mobilatolye.android.enuygun:id/radioGroupFlightTypeOneWay']");
    public static By goBack = By.xpath("//android.widget.RadioButton[@resource-id='com.mobilatolye.android.enuygun:id/radioGroupFlightTypeTwoWay']");
    public static By moreFly = By.xpath("//android.widget.RadioButton[@resource-id='com.mobilatolye.android.enuygun:id/radioGroupMultiDestination']");
    public static By fromWhereBtn = By.xpath("//android.widget.FrameLayout[@resource-id='com.mobilatolye.android.enuygun:id/flight_search_departure_button']");
    public static By whereArea = By.xpath("//android.widget.EditText[@content-desc='airport_selection_search_text']");
    public static By chooseCity = By.xpath("//android.view.ViewGroup[@resource-id='com.mobilatolye.android.enuygun:id/airport_selection_airport_cell']");
    public static By toWhereBtn = By.xpath("//android.widget.FrameLayout[@resource-id='com.mobilatolye.android.enuygun:id/flight_search_return_button']");
    public static By chooseToCity = By.xpath("(//android.view.ViewGroup[@resource-id='com.mobilatolye.android.enuygun:id/airport_selection_airport_cell'])[2]");
    public static By fromDate = By.xpath("//android.widget.FrameLayout[@resource-id='com.mobilatolye.android.enuygun:id/flight_search_departure_date_btn']/android.widget.FrameLayout/android.widget.LinearLayout");
    //public static By fromDay = By.xpath("//android.widget.TextView[@content-desc='activeDepartureDay = 44']");
    public static By fromDay = By.xpath("//android.widget.TextView[@text='20']");
    public static By toDate = By.xpath("//android.widget.FrameLayout[@resource-id='com.mobilatolye.android.enuygun:id/flight_search_return_date_btn']");
    public static By toDay = By.xpath("//android.widget.TextView[@content-desc='activeReturnDay = 5']");
    public static By addPassengetBtn = By.xpath("//android.widget.LinearLayout[@resource-id='com.mobilatolye.android.enuygun:id/flight_add_passenger_button']");
    public static By passengersCounts = By.xpath("//android.widget.ScrollView/android.widget.LinearLayout");
    public static By plusPassengers = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/flight_passenger_adult_plus_btn']");
    public static By minusPassengers = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/flight_passenger_adult_minus_btn']");
    public static By plusChild = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/flight_passenger_child_plus_btn']");
    public static By minusChild = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/flight_passenger_child_minus_btn']");
    public static By plusBaby = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/flight_passenger_infant_plus_btn']");
    public static By minusBaby = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/flight_passenger_infant_minus_btn']");
    public static By bussinesFly = By.xpath("//android.widget.RadioButton[@resource-id='com.mobilatolye.android.enuygun:id/class_BUSINESS']");
    public static By economicFly = By.xpath("//android.widget.RadioButton[@resource-id='com.mobilatolye.android.enuygun:id/class_ECONOMY']");
    public static By apply = By.xpath("//android.widget.Button[@resource-id='com.mobilatolye.android.enuygun:id/flight_passenger_and_class_apply_button']");
    public static By onlyDirctFlight = By.xpath("//android.widget.CheckBox[@resource-id='com.mobilatolye.android.enuygun:id/flight_add_show_only_direct_flights']");
    public static By findCheaperFlight = By.xpath("//android.widget.Button[@resource-id='com.mobilatolye.android.enuygun:id/flight_btn_search']");
    public static By fromTicket = By.xpath("(//android.view.ViewGroup[@resource-id='com.mobilatolye.android.enuygun:id/constraintLayout9'])[1]");
    //public static By superEcoTicket = By.xpath("//android.widget.FrameLayout[@content-desc='flight_bff_basic']/android.view.ViewGroup");
    public static By superEcoTicket = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.mobilatolye.android.enuygun:id/recycler_view']/android.widget.FrameLayout/android.view.ViewGroup");
    public static By toTicket = By.xpath("(//android.view.ViewGroup[@resource-id='com.mobilatolye.android.enuygun:id/constraintLayout9'])[1]");
    public static By priceOfTicket = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/btn_search_detail_total_price_label']");
    public static By continueForBuy = By.xpath("//android.view.ViewGroup[@resource-id='com.mobilatolye.android.enuygun:id/btn_search_detail_continue']");
    public static By passengersInfoTitle = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/txt_hotel_reservation_page_title']");
    public static By eMailForInfo = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/flight_reservation_email']");
    public static By numberForInfo = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/contact_phone_number']");
    public static By nameOfPassengers = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/flight_reservation_passenger_name']");
    public static By surnameOfPassengers = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/flight_reservation_passenger_last_name']");
    public static By birhdayOfPassengers = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/flight_reservation_passenger_birth_date']");
    public static By okeyForBirthBtn = By.xpath("//android.widget.Button[@resource-id='android:id/button1']");
    public static By nationalIdOfPassengers = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/flight_reservation_citizen_number']");
    public static By femaleOfPassengers = By.xpath("//android.widget.RadioButton[@resource-id='com.mobilatolye.android.enuygun:id/female_button']");
    public static By maleOfPassengers = By.xpath("//android.widget.RadioButton[@resource-id='com.mobilatolye.android.enuygun:id/male_button']");
    public static By continueForInfo = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/enBtnBack']");
    public static By standartSupport = By.xpath("//android.widget.Button[@content-desc='flight_add_product_sub_item_button_vip_0']");
    public static By firstSupport = By.xpath("//android.widget.Button[@content-desc='flight_add_product_sub_item_button_vip_1']");
    public static By addSecuityMyTicket = By.xpath("(//android.widget.CheckBox[@resource-id='com.mobilatolye.android.enuygun:id/checkBoxBtn'])");
    public static By giveMedicine = By.xpath("(//android.widget.CheckBox[@resource-id='com.mobilatolye.android.enuygun:id/checkBoxBtn'])[1]");
    public static By giveTicket = By.xpath("(//android.widget.CheckBox[@resource-id='com.mobilatolye.android.enuygun:id/checkBoxBtn'])[2]");
    public static By passPay = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/enBtnBack']");
    public static By creditCardNumber = By.xpath("//android.widget.FrameLayout[@resource-id='com.mobilatolye.android.enuygun:id/payment_fragment_container']/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout");
    public static By creditCardMonth = By.xpath("//android.widget.TextView[@content-desc='flight_payment_creditcard_expire_month']");
    //public static By chooseCardForMonth = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/customListItemText' and @text='10']");
    public static By chooseCardForMonth = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/customListItemText' and @text='04']");
    public static By creditCardYear = By.xpath("//android.widget.TextView[@content-desc='flight_payment_creditcard_expire_year']");
    //public static By chooseYearForYear = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/customListItemText' and @text='2035']");
    public static By chooseYearForYear = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/customListItemText' and @text='2027']");
    public static By creditCardCVV = By.xpath("//android.widget.EditText[@content-desc='flight_payment_creditcard_cvv_masterpass']");
    public static By  creditCardInstallment = By.xpath("//android.widget.EditText[@resource-id='com.mobilatolye.android.enuygun:id/installmentTextInput']");
    //public static By  sixMonthInstallment = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/customListItemText' and @text='6 Taksit: 6 x 560,20 TL']");
    public static By  sixMonthInstallment = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.mobilatolye.android.enuygun:id/list']/android.widget.FrameLayout[3]");
    public static By saveMyCard = By.xpath("//android.widget.CheckBox[@content-desc='flight_payment_creditcard_save_masterpass_checkbox']");
    //public static By buyTicket = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/btnTv']");
    public static By buyTicket = By.xpath("//android.widget.FrameLayout[@resource-id='com.mobilatolye.android.enuygun:id/enBtn']/android.view.ViewGroup/android.widget.LinearLayout");
    //public static By useDecrease = By.xpath("//android.widget.TextView[@resource-id='com.mobilatolye.android.enuygun:id/btnTv']");
    public static By errorForCard = By.xpath("//android.widget.ImageView[@resource-id='com.mobilatolye.android.enuygun:id/btn_close']");
    public static By payWithJuzdan = By.xpath("(//android.widget.LinearLayout[@resource-id='com.mobilatolye.android.enuygun:id/expand_button_layout'])[2]");
    public static By goComeback = By.id("com.mobilatolye.android.enuygun:id/radioGroupFlightTypeTwoWay");
    public static By payBackButton = By.id("com.mobilatolye.android.enuygun:id/back_button");
    public static By backSearchResult = By.id("com.mobilatolye.android.enuygun:id/btnGoToHomePage");
    public static By otelTab = By.xpath("//android.widget.LinearLayout[@content-desc='Otel']");
    public static By searchCityForOtel = By.id("com.mobilatolye.android.enuygun:id/hotel_search_location_button");
    public static By whichCityStay = By.id("com.mobilatolye.android.enuygun:id/edtSearch");
    public static By chooseHotel = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.mobilatolye.android.enuygun:id/recyclerviewSearchHotels']/android.view.ViewGroup[3]");
    public static By hotelFirstDate = By.id("com.mobilatolye.android.enuygun:id/hotel_search_checkin_button");
    public static By seeCalenderForHotel = By.id("com.mobilatolye.android.enuygun:id/calendar_view_title");
    public static By chooseHotelFirstDay = By.xpath("//android.widget.TextView[@text = '20']");
    public static By chooseHotelLeaveDay = By.xpath("//android.widget.TextView[@text = '23']");
    public static By chooseHotelOkey = By.id("com.mobilatolye.android.enuygun:id/calendarApplyButton");
    public static By chooseHotelGuest = By.id("com.mobilatolye.android.enuygun:id/hotel_search_add_guest_button");
    public static By chooseHotelAdultPlus = By.id("com.mobilatolye.android.enuygun:id/hotel_guest_adult_plus");
    public static By chooseHotelAdultMinus = By.id("com.mobilatolye.android.enuygun:id/hotel_guest_adult_minus");
    public static By chooseHotelChildPlus = By.id("com.mobilatolye.android.enuygun:id/hotel_guest_child_plus");
    public static By chooseHotelChildMinus = By.id("com.mobilatolye.android.enuygun:id/hotel_guest_child_minus");
    public static By chooseHotelApplyGuest = By.id("com.mobilatolye.android.enuygun:id/hotel_guest_apply_button");
    public static By searchHotelRooms = By.id("com.mobilatolye.android.enuygun:id/hotel_search_search_rooms");
    public static By sortedHotels = By.id("com.mobilatolye.android.enuygun:id/enFilterShort");
    public static By chooseSortedHotels = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.mobilatolye.android.enuygun:id/recycler_view_filter']/android.widget.LinearLayout[1]");
    public static By lookHotels = By.xpath("(//android.view.ViewGroup[@resource-id='com.mobilatolye.android.enuygun:id/layout_hotel_search_item'])[2]");
    public static By roomHotels = By.xpath("//android.widget.HorizontalScrollView[@resource-id='com.mobilatolye.android.enuygun:id/tabLayoutHotel']/android.widget.LinearLayout/android.widget.LinearLayout[1]");
    public static By infoHotels = By.xpath("//android.widget.HorizontalScrollView[@resource-id='com.mobilatolye.android.enuygun:id/tabLayoutHotel']/android.widget.LinearLayout/android.widget.LinearLayout[2]");
    public static By commentHotels = By.xpath("//android.widget.HorizontalScrollView[@resource-id='com.mobilatolye.android.enuygun:id/tabLayoutHotel']/android.widget.LinearLayout/android.widget.LinearLayout[3]");
    public static By reservationHotels = By.id("com.mobilatolye.android.enuygun:id/enBtnBack");
    public static By hotelPassengerName = By.id("com.mobilatolye.android.enuygun:id/txt_flight_passenger_list_item_passenger_name");
    public static By hotelPassengerSurname = By.id("com.mobilatolye.android.enuygun:id/txt_flight_passenger_list_item_passenger_surname");
    public static By genderMale = By.id("com.mobilatolye.android.enuygun:id/radio_flight_passenger_list_item_passenger_gender_male");
    public static By genderFemale = By.id("com.mobilatolye.android.enuygun:id/radio_flight_passenger_list_item_passenger_gender_female");
    public static By privateWantHotel = By.xpath("//android.widget.FrameLayout[@content-desc='hotel_customer_request_table_cell']/android.widget.ScrollView");
    public static By reservationRuleHotel = By.xpath("//android.widget.FrameLayout[@content-desc='hotel_reservation_policy_cell']/android.widget.ScrollView");
    public static By payInfoHotel = By.xpath("//android.widget.FrameLayout[@content-desc='hotel_reservation_invoice_cell']/android.widget.ScrollView");
    public static By payForHotel = By.id("com.mobilatolye.android.enuygun:id/btnComplete");
    public static By creditCardNumberHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[2]/android.view.View[1]/android.view.View/android.view.View/android.view.View/android.widget.EditText");
    public static By creditCardNumberMonthHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[1]/android.view.View[2]/android.view.View/android.view.View/android.view.View");
    public static By creditCardNumberLastMHotel = By.xpath("//android.widget.FrameLayout[@resource-id='android:id/custom']/android.widget.ListView/android.widget.CheckedTextView[4]");
    public static By creditCardNumberYearhHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.view.View/android.view.View/android.view.View");
    public static By creditCardNumberLastYHotel = By.xpath("//android.widget.FrameLayout[@resource-id='android:id/custom']/android.widget.ListView/android.widget.CheckedTextView[2]");
    public static By creditCardNumberCvvHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[2]/android.view.View[2]/android.view.View[3]/android.view.View/android.view.View/android.widget.EditText");
    public static By installmentHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[3]/android.widget.Button[3]");
    public static By decreaseHotel = By.xpath("//android.widget.TextView[@text='İndirim kodu kullan']");
    //public static By decreaseCodeHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[3]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.TextView[2]");
    //public static By decreaseCodeHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[4]/android.view.View");
    public static By decreaseCodeHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[4]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText");
    public static By decreaseCodeUseHotel = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[3]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText");
    public static By decreaseCodeUseHotels = By.xpath("//android.widget.Button[@text='Kullan']");
    public static By payForHotels = By.xpath("//android.widget.Button[@text='Ödeme yap']");
    public static By afterPay = By.xpath("//android.view.View[@resource-id='payment-form']/android.view.View/android.view.View/android.view.View[1]/android.view.View[2]");


}
